# Generated by Django 5.0 on 2024-01-09 13:24

import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=252)),
                ('fullname', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=250)),
                ('serial_document', models.CharField(max_length=255)),
                ('id_image', models.TextField()),
                ('address_image', models.TextField()),
                ('selfie_image', models.TextField()),
                ('is_identified', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('wallet_addres', models.CharField(blank=True, max_length=200, null=True)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('is_identified', models.BooleanField(blank=True, null=True)),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('referal_link', models.CharField(default=user.models.generate_random_string, editable=False, max_length=8, unique=True)),
                ('number_people', models.IntegerField(default=0)),
                ('balance_usdt', models.FloatField(default=0.0)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('last_mining', models.IntegerField(blank=True, default=0, null=True)),
                ('wallet_id_usdt', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wallet_id_netbo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_identified', models.BooleanField(default=False)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('balance_usdt', models.FloatField(default=0.0)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
